#document-management.chcy6s4g03hf.ap-southeast-2.rds.amazonaws.com
spring.datasource.url=${DB_URL_LOCAL}
#jdbc:postgresql://document-management.chcy6s4g03hf.ap-southeast-2.rds.amazonaws.com:5432/document_management?sslmode=require
spring.datasource.username=${DB_USERNAME_LOCAL}
spring.datasource.password=${DB_PASSWORD_LOCAL}