spring.application.name=document_management
#document-management.chcy6s4g03hf.ap-southeast-2.rds.amazonaws.com
spring.datasource.url=jdbc:postgresql://localhost:5432/document_management
#jdbc:postgresql://document-management.chcy6s4g03hf.ap-southeast-2.rds.amazonaws.com:5432/document_management?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=CRAZYBOBER@321
spring.jpa.hibernate.ddl-auto=update
#which actually prints the SQL
spring.jpa.show-sql=true
#The dialect setting tells Hibernate: “Use PostgreSQL‑specific SQL when talking to the database.”
#By default, Hibernate logs SQL as one long line, which is hard to read.

#With format_sql=true, Hibernate adds line breaks and indentation so you can clearly see the structure of the query.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#Driver class name (Spring Boot usually auto‑detects, but you can be explicit)
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#loi~ display 502 gateway error
#port default springboot: 8080, aws: 5000, kiem tra port aws o dau?